### ISSUE TITLE
Error running kpub-update

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/kpub#2]
I run kpub-update 2015-08 and the an error. It could be that ADS is really overloaded or it could be something is wrong. I've got an ads key and have the github version of ads installed

``` bash
INFO: Querying ADS for acknowledgements (month=2015-08). [kpub.kpub]
Traceback (most recent call last):
  File "/Users/tom/.virtualenvs/p1/bin/kpub-update", line 9, in <module>
    load_entry_point('kpub==1.0.0', 'console_scripts', 'kpub-update')()
  File "/Users/tom/.virtualenvs/p1/lib/python2.7/site-packages/kpub-1.0.0-py2.7.egg/kpub/kpub.py", line 424, in kpub_update
    PublicationDB(args.f).update(month=args.month)
  File "/Users/tom/.virtualenvs/p1/lib/python2.7/site-packages/kpub-1.0.0-py2.7.egg/kpub/kpub.py", line 277, in update
    articles = list(qry)
  File "build/bdist.macosx-10.10-x86_64/egg/ads/search.py", line 339, in next
  File "build/bdist.macosx-10.10-x86_64/egg/ads/search.py", line 348, in __next__
  File "build/bdist.macosx-10.10-x86_64/egg/ads/search.py", line 380, in execute
  File "build/bdist.macosx-10.10-x86_64/egg/ads/base.py", line 39, in load_http_response
ads.exceptions.APIResponseError: u'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>\n'
```

**Comment by barentsen** [comment]
The github version of ads has seen *major* changes earlier this month, because ADS is switching to a new API.

**Comment by barentsen** [comment]
The github version of `ads` has seen _major_ changes earlier this month, because ADS is switching to a new API.  I tried switching to this new version today, but ran into a bug quickly ( https://github.com/andycasey/ads/pull/25 )

If you want to use `kpub` today, it's better to remove the github version of `ads` you installed, and use the older version that is defined in `setup.py`:

git+https://github.com/barentsen/ads.git@ads-python3-20150630#egg=ads-1.0

... I just checked that this still works with no problem.

**Comment by barentsen** [comment]
As of a few minutes ago, the bug in `ads` has been fixed and `kpub` has been adapted to the new API. Things should work again if you install the latest git of both packages.  Do reopen this issue if it doesn't!
