### ISSUE TITLE
error when making kpub for keplerwebsite

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/kpub#4]
``` bash
 ~/w/KeplerScienceWebsite> make kpub
cd content/pages/kpub; \
    kpub --save
/Users/tom/.virtualenvs/p1/lib/python2.7/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
INFO: Writing kpub-by-month.md [kpub.kpub]
INFO: Writing kpub-exoplanets-by-month.md [kpub.kpub]
INFO: Writing kpub-astrophysics-by-month.md [kpub.kpub]
INFO: Writing kpub-kepler-by-month.md [kpub.kpub]
INFO: Writing kpub-k2-by-month.md [kpub.kpub]
INFO: Writing kpub.md [kpub.kpub]
INFO: Writing kpub-exoplanets.md [kpub.kpub]
INFO: Writing kpub-astrophysics.md [kpub.kpub]
INFO: Writing kpub-kepler.md [kpub.kpub]
INFO: Writing kpub-k2.md [kpub.kpub]
Traceback (most recent call last):
  File "/Users/tom/.virtualenvs/p1/bin/kpub", line 9, in <module>
    load_entry_point('kpub==1.0.0', 'console_scripts', 'kpub')()
  File "/Users/tom/.virtualenvs/p1/lib/python2.7/site-packages/kpub-1.0.0-py2.7.egg/kpub/kpub.py", line 541, in kpub
    template = env.get_template('template-overview.md')
  File "/Users/tom/.virtualenvs/p1/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/tom/.virtualenvs/p1/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/tom/.virtualenvs/p1/lib/python2.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: template-overview.md
make: *** [kpub] Error 1
```

**Comment by mrtommyb** [comment]
is this fixed yet @barentsen ?

**Comment by mrtommyb** [comment]
There is now a new error

``` bash
Traceback (most recent call last):
  File "/Users/tom/.virtualenvs/p1/bin/kpub", line 9, in <module>
    load_entry_point('kpub==1.0.0', 'console_scripts', 'kpub')()
  File "/Users/tom/.virtualenvs/p1/lib/python2.7/site-packages/kpub-1.0.0-py2.7.egg/kpub/kpub.py", line 550, in kpub
    f.write(markdown)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 4312: ordinal not in range(128)
make: *** [kpub] Error 1
```

**Comment by mrtommyb** [comment]
Still isn't fixed @barentsen

**Comment by barentsen** [comment]
Can you copy/paste error message? ad0fed8f936630638f33bd1e11f501f91c87e423 should have fixed the `ascii` codec problem.

**Comment by barentsen** [comment]
Oops, there was still a problem. 4766a3097fb759ee5c391c39f142c2f1adabae9d fixes this issue.  I verified under Python 2 and 3.

**Comment by barentsen** [comment]
@mrtommyb Please verify and close issue at your convenience.
